# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx2G -XX:+UseG1GC -XX:MaxMetaspaceSize=512m
org.gradle.parallel=true
org.gradle.caching=true

group=cc.turtl.chiselmon

# API
mc_version = 1.21.1
parchment_version = 2024.07.28@zip
# Used in mod files
java_version = 21

mod_id=chiselmon
mod_display_name=Chiselmon
mod_version=1.3.0
mod_author=megaturtl
mod_description=Cobblemon alerts, tooltips, PC bookmarks, wallpapers, and much more. Fully customisable and client side.
snapshot=true

fabric.loom.multiProjectOptimisation=true

# Mod implementation dependencies
yacl_version=3.8.1+1.21.1