modLoader = "kotlinforforge"
loaderVersion = "[5.3,)"
issueTrackerURL = "https://github.com/megaturtl/chiselmon/issues"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_display_name}"
authors = "${mod_author}"
description = "Sculpt your perfect Cobblemon experience with deeply customisable QOL tweaks!"
logoFile="assets/chiselmon/icon.png"

[[dependencies.chiselmon]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version}]"

[[dependencies.chiselmon]]
modId = "neoforge"
mandatory = true
versionRange = "[21,)"

[[dependencies.chiselmon]]
modId = "turtlshell"
mandatory = true
versionRange = "[1.0.0,)"

[[dependencies.chiselmon]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.7.0,)"

[[dependencies.chiselmon]]
modId = "yet_another_config_lib_v3"
mandatory = true
versionRange = "[3.6.1,)"
side = "CLIENT"

[[dependencies.chiselmon]]
modId = "jade"
type = "optional"
versionRange = "[15.10.2,)"

[[mixins]]
config = "chiselmon-neoforge.mixins.json"
[[mixins]]
config = "chiselmon-common.mixins.json"
